-- Основные сетевые сообщения
util.AddNetworkString("ArrestMaster_OpenMenu")
util.AddNetworkString("ArrestMaster_CloseMenu")
util.AddNetworkString("ArrestMaster_UpdateList")
util.AddNetworkString("ArrestMaster_ArrestPlayer")
util.AddNetworkString("ArrestMaster_ReleasePlayer")
util.AddNetworkString("ArrestMaster_UpdateTime")
util.AddNetworkString("ArrestMaster_Notify")
util.AddNetworkString("ArrestMaster_LogAction")
util.AddNetworkString("ArrestMaster_UpdateCamera")
util.AddNetworkString("ArrestMaster_RequestCamera")
util.AddNetworkString("ArrestMaster_UpdateEscapeStatus")
util.AddNetworkString("ArrestMaster_EscapeAttempt")
util.AddNetworkString("ArrestMaster_EscapeSuccess")
util.AddNetworkString("ArrestMaster_EscapeFail")
util.AddNetworkString("ArrestMaster_UpdateMinigameStatus")
util.AddNetworkString("ArrestMaster_RequestMinigame")
util.AddNetworkString("ArrestMaster_StartMinigame")
util.AddNetworkString("ArrestMaster_CompleteMinigame")
util.AddNetworkString("ArrestMaster_MinigameResult")

-- Сетевые сообщения для мини-игр
util.AddNetworkString("ArrestMaster_MemoryGame")
util.AddNetworkString("ArrestMaster_MathGame")
util.AddNetworkString("ArrestMaster_TypingGame")
util.AddNetworkString("ArrestMaster_PuzzleGame") 